# Comment
FROM maven:3.6.3-ibmjava-8-alpine AS MAVEN_BUILDER

WORKDIR /build/

COPY pom.xml /build/
COPY src /build/src/

RUN mvn package
RUN  mkdir dockerVolume
RUN pwd
RUN ls
    
COPY --from=MAVEN_BUILDER target/ /dockerVolume/testResults
VOLUME /dockerVolume



#FROM openjdk:15-jdk-alpine

#WORKDIR /app

#COPY --from=MAVEN_BUILDER /build/target/spring-hello-1.0.0.jar /app/

#ENTRYPOINT ["java", "-jar", "spring-hello-1.0.0.jar"]
